### ISSUE TITLE
CODACY Improvements

### ISSUE THREAD

**Issue by peisenha** [briqInstitute/interalpy#12]
Please tackle some of the comments/suggestions from here https://www.codacy.com/app/eisenhauer/interalpy/dashboard We will not incorporate all of them, but some are obvious improvements.

**Comment by DennisKubitza** [comment]
Started with them.
Remaining are only the issues concering security and unused code parts. Many of the mare related to the usage of  git -clean in the console. 

I'll carry on fixing other issues that arise.

**Comment by peisenha** [comment]
- please do not modify setup.py, add it to the ignored file, see configuration here https://support.codacy.com/hc/en-us/articles/115002130625-Codacy-Configuration-File
- we discussed some additional steps

**Comment by peisenha** [comment]
Please close this if you merged your work form the relevant branch ...

**Comment by peisenha** [comment]
We are still stuck with a B, please get up to A.

**Comment by peisenha** [comment]
Pleae make sure we can merge your branch into master and get an A in our meeting later this week.

**Comment by peisenha** [comment]
This is done.
